name: CI

on:
  push:

jobs:
  lints:
    name: Formatting + Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Test
        run: pwd
